CREATE TABLE "CronLog" (
  "id" TEXT NOT NULL,
  "runAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "checked" INTEGER NOT NULL,
  "queued" INTEGER NOT NULL,
  "errors" INTEGER NOT NULL DEFAULT 0,
  "durationMs" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "CronLog_pkey" PRIMARY KEY ("id")
);
